name: GameTest
on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUN_SERVER: RUN_SERVER
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java 21
        uses: actions/setup-java@v4.2.1
        with:
          distribution: zulu
          java-version: 21

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run GameTest
        run: ./gradlew runGameTestServer